config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "boards#index"

  resources :boards do
    resources :pins
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  def username
    self.email.split("@")[0]
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boards
  has_many :pins, through: :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  def index
    @boards=Board.all
  end

  def new
    @board=Board.new
  end

  def create
    @board=Board.create(board_params)

    redirect_to board_path(@board)
  end

  def show
    @board=Board.find(params[:id])
    @pins = @board.pins
  end

  def destroy
    @board = Board.find(params[:id])
    @pins = @board.pins
    @pins.destroy_all
    @board.destroy
    redirect_to boards_path
  end

  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    redirect_to @board
  end

  def edit
    @board = Board.find(params[:id])
  end

  private
  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @board=Board.find(params[:board_id])
    @pin=Pin.all
  end

  def new
    @board=Board.find(params[:board_id])
    @pin=Pin.new
  end

  def edit
    @board=Board.find(params[:board_id])
    @pin=Pin.find(params[:id])
  end

  def create
    @board=Board.find(params[:board_id])
    @pin=@board.pins.create(pin_params)
    redirect_to board_pin_path(@board, @pin)
  end

  def show
    @board=Board.find(params[:board_id])
    @pin=Pin.find(params[:id])
  end

  def update
    @board=Board.find(params[:board_id])
    @pin=Pin.find(params[:id])
    @pin.update(pin_params)
    redirect_to @board
  end

  def destroy
    @pin=Pin.find(params[:id])
    @board = @pin.board
    @pin.destroy
    redirect_to @board
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :pin_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<%end%>

app/views/boards/edit.html.erb
<%= render 'form' %>

app/views/boards/index.html.erb
<%= link_to "Create board", new_board_path %>
<% @boards.each do |board|%>
  <ul>
    <li><%= link_to board.title, board_path(board) %></li>
  </ul>
<% end %>

app/views/boards/new.html.erb
<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<%end%>

app/views/boards/show.html.erb
<h2><%= @board.title %></h2>
<%= link_to "Input Samir here", new_board_pin_path(@board) %>

<ul>
  <% @pins.each do |pin| %>
    <h3><%= pin.title %></h3>
    <%= image_tag "#{pin.pin_url}", alt: "#{pin.title} picture", class: "pin-picture" %>
    <div><%= link_to "edit samir", edit_board_pin_path(@board, pin) %></div>
    <div><%= link_to "delete samir", board_pin_path(@board, pin), method: "delete" %></div>
  <% end %>
</ul>


<h4>One Won</h4>
<div><%= link_to "edit board", edit_board_path(@board) %></div>
<div><%= link_to "delete board", board_path(@board), method: "delete" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinspiration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <button class='click'>Click</button>
  <%= link_to "Boards", boards_path %>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for [@board, @pin] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :pin_url %>
  <%= f.text_field :pin_url  %>

  <%= f.submit %>
<%end%>

app/views/pins/edit.html.erb
<%= render 'form' %>

app/views/pins/index.html.erb
<h2> Thats a lie</h2>

app/views/pins/new.html.erb
<%= render 'form' %>

app/views/pins/show.html.erb
<h2><%= @pin.title %></h2>
<%= image_tag "#{@pin.pin_url}", alt: "#{@pin.title} image"%>